


cols_to_convert <- c(
  "RH.LATERALORBITOFRONTAL", "RH.PARSORBITALIS", "RH.FRONTALPOLE",
  "RH.MEDIALORBITOFRONTAL", "RH.PARSTRIANGULARIS", "RH.PARSOPERCULARIS",
  "RH.ROSTRALMIDDLEFRONTAL", "RH.SUPERIORFRONTAL", "RH.CAUDALMIDDLEFRONTAL",
  "RH.PRECENTRAL", "RH.PARACENTRAL", "RH.ROSTRALANTERIORCINGULATE",
  "RH.CAUDALANTERIORCINGULATE", "RH.POSTERIORCINGULATE", "RH.ISTHMUSCINGULATE",
  "RH.POSTCENTRAL", "RH.SUPRAMARGINAL", "RH.SUPERIORPARIETAL",
  "RH.INFERIORPARIETAL", "RH.PRECUNEUS", "RH.CUNEUS",
  "RH.PERICALCARINE", "RH.LATERALOCCIPITAL", "RH.LINGUAL",
  "RH.FUSIFORM", "RH.PARAHIPPOCAMPAL", "RH.ENTORHINAL",
  "RH.TEMPORALPOLE", "RH.INFERIORTEMPORAL", "RH.MIDDLETEMPORAL",
  "RH.BANKSSTS", "RH.SUPERIORTEMPORAL", "RH.TRANSVERSETEMPORAL",
  "RH.INSULA", "RIGHT-THALAMUS-PROPER", "RIGHT-CAUDATE",
  "RIGHT-PUTAMEN", "RIGHT-PALLIDUM", "RIGHT-ACCUMBENS-AREA",
  "RIGHT-HIPPOCAMPUS", "RIGHT-AMYGDALA",
  "LH.LATERALORBITOFRONTAL", "LH.PARSORBITALIS", "LH.FRONTALPOLE",
  "LH.MEDIALORBITOFRONTAL", "LH.PARSTRIANGULARIS", "LH.PARSOPERCULARIS",
  "LH.ROSTRALMIDDLEFRONTAL", "LH.SUPERIORFRONTAL", "LH.CAUDALMIDDLEFRONTAL",
  "LH.PRECENTRAL", "LH.PARACENTRAL", "LH.ROSTRALANTERIORCINGULATE",
  "LH.CAUDALANTERIORCINGULATE", "LH.POSTERIORCINGULATE", "LH.ISTHMUSCINGULATE",
  "LH.POSTCENTRAL", "LH.SUPRAMARGINAL", "LH.SUPERIORPARIETAL",
  "LH.INFERIORPARIETAL", "LH.PRECUNEUS", "LH.CUNEUS",
  "LH.PERICALCARINE", "LH.LATERALOCCIPITAL", "LH.LINGUAL",
  "LH.FUSIFORM", "LH.PARAHIPPOCAMPAL", "LH.ENTORHINAL",
  "LH.TEMPORALPOLE", "LH.INFERIORTEMPORAL", "LH.MIDDLETEMPORAL",
  "LH.BANKSSTS", "LH.SUPERIORTEMPORAL", "LH.TRANSVERSETEMPORAL",
  "LH.INSULA", "LEFT-THALAMUS-PROPER", "LEFT-CAUDATE",
  "LEFT-PUTAMEN", "LEFT-PALLIDUM", "LEFT-ACCUMBENS-AREA",
  "LEFT-HIPPOCAMPUS", "LEFT-AMYGDALA", "BRAIN-STEM"
)

regions = cols_to_convert

# stages from groth 2017
stage_I <- c(
  "ENTORHINAL", "PARAHIPPOCAMPAL", "TEMPORALPOLE",
  "MEDIALORBITOFRONTAL", "LATERALORBITOFRONTAL", "PARSORBITALIS",
  "FRONTALPOLE", "ROSTRALANTERIORCINGULATE", "CAUDALANTERIORCINGULATE"
)

stage_II <- c(
  "SUPERIORFRONTAL", "ROSTRALMIDDLEFRONTAL", "CAUDALMIDDLEFRONTAL",
  "PARSTRIANGULARIS", "PARSOPERCULARIS",
  "MIDDLETEMPORAL", "INFERIORTEMPORAL", "BANKSSTS", "SUPERIORTEMPORAL",
  "FUSIFORM",
  "INFERIORPARIETAL", "SUPRAMARGINAL", "SUPERIORPARIETAL", "PRECUNEUS",
  "POSTERIORCINGULATE", "ISTHMUSCINGULATE",
  "INSULA", "LATERALOCCIPITAL"
)

stage_III <- c(
  "HIPPOCAMPUS", "AMYGDALA",
  "PRECENTRAL", "POSTCENTRAL", "PARACENTRAL",
  "TRANSVERSETEMPORAL",
  "PERICALCARINE", "CUNEUS", "LINGUAL"
)

stage_IV <- c(
  "CAUDATE", "PUTAMEN", "PALLIDUM", "ACCUMBENS-AREA", "ACcUMBENS" #DK parcellation difference (ASEG)
)

# Regions outside the Grothe model
stage_0_explicit <- c(
  "THALAMUS-PROPER",   
  "BRAIN-STEM", "THALAMUS"
)